spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    url: jdbc:mysql://xxxx:3306/sync_trajectory_backend?useSSL=false
    username: thr
    password: xxxx
  # session 失效时间
  session:
    timeout: 86400
  profiles:
    active: prod

server:
  address: 0.0.0.0
